
/* 
   Native symbol registration table for spatstat.univar package

   Automatically generated - do not edit this file!

*/

#include "proto.h"
#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*  
   See proto.h for declarations for the native routines registered below.
*/

static const R_CMethodDef CEntries[] = {
    {"adaptiveKDE",     (DL_FUNC) &adaptiveKDE,      9},
    {"adaptKDEbdry",    (DL_FUNC) &adaptKDEbdry,     9},
    {"adaptKDEconvol",  (DL_FUNC) &adaptKDEconvol,   9},
    {"adaptKDEreflect", (DL_FUNC) &adaptKDEreflect,  9},
    {"adaptKDEweight",  (DL_FUNC) &adaptKDEweight,   9},
    {"bcolonel",        (DL_FUNC) &bcolonel,        13},
    {"colonel",         (DL_FUNC) &colonel,          8},
    {"fbcolonel",       (DL_FUNC) &fbcolonel,       13},
    {"fcolonel",        (DL_FUNC) &fcolonel,         8},
    {"hotrodAbsorb",    (DL_FUNC) &hotrodAbsorb,     7},
    {"hotrodInsul",     (DL_FUNC) &hotrodInsul,      7},
    {"kermom",          (DL_FUNC) &kermom,           8},
    {"tabsumweight",    (DL_FUNC) &tabsumweight,     6},
    {"taylorboot",      (DL_FUNC) &taylorboot,       5},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"Cwhist", (DL_FUNC) &Cwhist, 3},
    {NULL, NULL, 0}
};

void R_init_spatstat_univar(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE); 
}
