
/* 
   Native symbol registration table for spatstat.univar package

   Automatically generated - do not edit this file!

*/

#include "proto.h"
#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*  
   See proto.h for declarations for the native routines registered below.
*/

static const R_CMethodDef CEntries[] = {
    {"hotrodAbsorb", (DL_FUNC) &hotrodAbsorb, 7},
    {"hotrodInsul",  (DL_FUNC) &hotrodInsul,  7},
    {"tabsumweight", (DL_FUNC) &tabsumweight, 6},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"Cwhist", (DL_FUNC) &Cwhist, 3},
    {NULL, NULL, 0}
};

void R_init_spatstat_univar(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE); 
}
